services:
  # =================================================
  # POSTGRES SERVER
  # =================================================
  pg-docker:
    user: root
    image: postgres:16.1-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - app:/data/app-db
    networks:
      - dev-network

# =================================================
# REDE
# =================================================
networks:
  dev-network:
    driver: bridge

volumes:
  app:
